trigger: none

resources:
  pipelines:
    - pipeline: LostCrypt
      project: LostCrypt
      source: LostCrypt iOS Release

variables:
  - template: variables.yml

jobs:
  - job: iOSXcodeBuild
    pool:
      vmImage: macOS-latest
    steps:
      - template: steps-xcode.yml
        parameters:
          download: LostCrypt
          publish: ios
