trigger: none

parameters:
  - name: config
    type: string
    default: Development
    values: [Development, Release]

variables:
  - template: variables.yml

jobs:
  - job: AndroidUnityBuild
    pool:
      name: UnityWindowsPool1
    steps:
      - checkout: self
        lfs: true
      - template: steps-disk.yml
      - template: steps-unity.yml
        parameters:
          target: Android
          config: ${{parameters.config}}
          publish: android
