trigger: none

parameters:
  - name: pool
    type: string
    default: UnityWindowsPool1
  - name: config
    type: string
    default: Development
    values: [Development, Release]

variables:
  - template: variables.yml

jobs:
  - job: AndroidUnityBuild
    pool:
      name: ${{parameters.pool}}
    steps:
      - checkout: self
        lfs: true
      - template: steps-disk.yml
      - template: steps-unity.yml
        parameters:
          target: Android
          config: ${{parameters.config}}
          publish: android
      - template: steps-appcenter.yml
        parameters:
          target: Android
          config: ${{parameters.config}}
          file: Output/*.apk
