trigger: none

parameters:
  - name: pool
    type: string
    default: UnityWindowsPool1
  - name: config
    type: string
    default: Development
    values: [Development, Release]

variables:
  - template: variables.yml

jobs:
  - job: iOSUnityBuild
    pool:
      name: ${{parameters.pool}}
    steps:
      - checkout: self
        lfs: true
      - template: steps-disk.yml
      - template: steps-unity.yml
        parameters:
          target: iOS
          config: ${{parameters.config}}
          publish: xcode
  - job: iOSXcodeBuild
    dependsOn: iOSUnityBuild
    pool:
      vmImage: macOS-latest
    steps:
      - template: steps-xcode.yml
        parameters:
          download: current
          publish: ios
      - template: steps-appcenter.yml
        parameters:
          target: iOS
          config: ${{parameters.config}}
          file: export/*.ipa
